version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db-container
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci


volumes:
  mysql-data: